name: face_graph_test

description: A FaceGraph test for Flutter developer position [by Mohamad Allahham].

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.6
  flutter_bloc: ^7.0.1
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  moor_flutter: ^4.0.0
  syncfusion_flutter_datepicker: ^19.4.41
  image_picker: ^0.8.4+4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  moor_generator: ^4.6.0+1
  build_runner: ^2.1.7


flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/